name: Lint

on: [push, workflow_call]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint with shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './src'
