name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  publish:
    name: Publish to npmjs.org
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Setup .npmrc
      run: cp tools/_.npmrc .npmrc
    - name: Build the release
      run: mkdir dist && cp -a src/git-release README.md dist/
    - name: Configure the package.json for publishing
      run: jq 'del(.devDependencies,.scripts,.private)' package.json > dist/package.json
    - name: Publish the package
      run: yarn publish --access public --no-git-tag-version --new-version "${REF#refs\/tags\/v}"
      env:
        REF: ${{ github.ref }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_RW }}
      working-directory: dist

  create-release:
    name: Create GitHub Release
    needs: [lint, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Determine tag name
        id: tag-name
        env:
          REF: ${{ github.ref }}
        run: |
          printf "::set-output name=tag::%s\n" "$(basename "${{ github.ref }}")"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.tag-name.outputs.tag }}
      - name: Get release notes from tag
        id: tag-message
        env:
          REF: ${{ github.ref }}
        run: |
          MESSAGE=$(git tag -l --format='%(contents)' "${{ steps.tag-name.outputs.tag }}")
          MESSAGE=${MESSAGE//'%'/'%25'}
          MESSAGE=${MESSAGE//$'\n'/'%0A'}
          MESSAGE=${MESSAGE//$'\r'/'%0D'}
          printf "::set-output name=message::%s\n" "$MESSAGE"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-name.outputs.tag }}
          release_name: ${{ steps.tag-name.outputs.tag }}
          body: ${{ steps.tag-message.outputs.message }}
          draft: false
          prerelease: false
