name: Compile & publish

on:
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Determine tag name
        id: tag-name
        env:
          REF: ${{ github.ref }}
        run: |
          printf "::set-output name=tag::%s\n" "$(basename "${{ github.ref }}")"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.tag-name.outputs.tag }}
      - name: Get release notes from tag
        id: tag-message
        env:
          REF: ${{ github.ref }}
        run: |
          MESSAGE=$(git tag -l --format='%(contents)' "${{ steps.tag-name.outputs.tag }}")
          MESSAGE=${MESSAGE//'%'/'%25'}
          MESSAGE=${MESSAGE//$'\n'/'%0A'}
          MESSAGE=${MESSAGE//$'\r'/'%0D'}
          printf "::set-output name=message::%s\n" "$MESSAGE"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-name.outputs.tag }}
          release_name: ${{ steps.tag-name.outputs.tag }}
          body: ${{ steps.tag-message.outputs.message }}
          draft: false
          prerelease: false

  publish:
    name: Publish to npmjs.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Build the release
      run: tools/build.sh
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_RO }}
    - name: Set release version from tag name
      env:
        REF: ${{ github.ref }}
      run: jq --arg version "${REF/#refs\/tags\/v/}" '.version=$version' package.json > package.new.json && mv package.new.json package.json
      working-directory: dist
    - name: Setup .npmrc
      run: cp tools/_.npmrc dist/.npmrc
    - name: Publish the package
      run: yarn publish --new-version "$(jq -r .version package.json)"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_RW }}
      working-directory: dist
