name: Test

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - uses: orbit-online/upkg-install@v1
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
    - name: Show --help menu
      run: bin/git-release --help
